---
title: Privacy policy
---

I (Martin Řanda or rnd195) **do not** collect any personal data from visitors of this website.

This website is hosted using GitHub Pages. Please note that the host may collect personal data as described in the [documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages) for GitHub Pages:

> When a GitHub Pages site is visited, the visitor's IP address is logged and stored for security purposes, regardless of whether the visitor has signed into GitHub or not. For more information about GitHub's security practices, see [GitHub Privacy Statement](https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement).

This website may contain links to third-party websites. Please note that once you leave this site and access these external websites, this privacy policy no longer applies.

I take special care to ensure all content is served from this GitHub Pages site and not from additional third parties (other than GitHub itself). This is primarily done by an automated check executed during the website's build process. If you see any externally served resources (other than from GitHub itself), please report them to *contact`@`rnd195.anonaddy.com* so I can investigate and fix the issue promptly.

I may update this privacy policy from time to time. Any changes will be posted on this page with a revised effective date. If you have any questions or concerns regarding this privacy policy, please contact me at *contact`@`rnd195.anonaddy.com*.

Last updated: 14 Nov 2025
